# Generated by Django 2.2 on 2019-04-27 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20190427_1723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Ciudades'},
        ),
    ]
