# Generated by Django 2.2 on 2019-04-27 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Direcciones'},
        ),
    ]
