# Generated by Django 2.2 on 2019-04-30 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_remove_address_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
