# Generated by Django 2.2 on 2019-05-02 00:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0006_address_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtCollector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='person.Person', verbose_name='Persona')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('debt_collector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='role.DebtCollector', verbose_name='Cobrador')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='person.Person', verbose_name='Persona')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
