# Generated by Django 2.2 on 2019-04-27 19:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0005_auto_20190427_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('first_name', models.CharField(max_length=128, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=128, verbose_name='Apellido')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='common.Address', verbose_name='Dirección')),
            ],
            options={
                'verbose_name_plural': 'Personas',
            },
        ),
    ]
