# Generated by Django 2.2 on 2019-04-30 22:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_remove_address_city'),
        ('person', '0004_auto_20190430_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='address',
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('street_number', models.IntegerField(verbose_name='Número')),
                ('route', models.CharField(max_length=128, verbose_name='Calle')),
                ('unit', models.CharField(max_length=32, verbose_name='Unidad')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.City', verbose_name='Ciudad')),
            ],
            options={
                'verbose_name_plural': 'Direcciones',
            },
        ),
    ]
